channels:
  - conda-forge
  - bioconda

dependencies:
  - manta=1.1.0
  - delly=0.7.7
  - lumpy-sv=0.2.13
  - samblaster=0.1.24
  - gridss=1.3.4
  - bwa=0.7.15
  - r=3.5.1
  - survivor=1.0.6
  - samtools=1.9
  - bcftools=1.9
